server:
  port: 8031
spring:
  application:
    name: order-service-feign-hystrix-dashbord
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*" # * 在yaml 文件属于关键字
